package utils

var MINING_DIFFICULT = 0x8888

const MINING_ACCOUNT_ADDRESS = "YUANSHUO BLOCKCHAIN"
const MINING_REWARD = 5000
const MINING_TIMER_SEC = 10
const SAVEBLOCKFILE = "ys-blockchain.txt"
const (
	//以下参数可以添加到启动参数
	BLOCKCHAIN_PORT_RANGE_START      = 5000
	BLOCKCHAIN_PORT_RANGE_END        = 5003
	NEIGHBOR_IP_RANGE_START          = 0
	NEIGHBOR_IP_RANGE_END            = 0
	BLOCKCHIN_NEIGHBOR_SYNC_TIME_SEC = 10
)
